# Generated by Django 4.2.7 on 2023-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mammals',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taxon_id', models.CharField(max_length=255)),
                ('organism_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255, null=True)),
                ('url_download', models.TextField()),
            ],
            options={
                'ordering': ['taxon_id'],
            },
        ),
    ]
